[2024-08-01T14:33:18.353+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T14:33:18.407+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_etl.upload_to_gcs scheduled__2023-01-04T00:00:00+00:00 [queued]>
[2024-08-01T14:33:18.427+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_etl.upload_to_gcs scheduled__2023-01-04T00:00:00+00:00 [queued]>
[2024-08-01T14:33:18.427+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-01T14:33:18.454+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_gcs> on 2023-01-04 00:00:00+00:00
[2024-08-01T14:33:18.487+0000] {standard_task_runner.py:57} INFO - Started process 406 to run task
[2024-08-01T14:33:18.497+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nyc_taxi_etl', 'upload_to_gcs', 'scheduled__2023-01-04T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_etl.py', '--cfg-path', '/tmp/tmpgsgxizgf']
[2024-08-01T14:33:18.508+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask upload_to_gcs
[2024-08-01T14:33:18.554+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T14:33:18.662+0000] {task_command.py:410} INFO - Running <TaskInstance: nyc_taxi_etl.upload_to_gcs scheduled__2023-01-04T00:00:00+00:00 [running]> on host 31f8257a797f
[2024-08-01T14:33:18.692+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T14:33:19.506+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_taxi_etl' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2023-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-04T00:00:00+00:00'
[2024-08-01T14:33:19.513+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: upload_to_gcs() missing 1 required positional argument: 'credentials'
[2024-08-01T14:33:19.538+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_taxi_etl, task_id=upload_to_gcs, execution_date=20230104T000000, start_date=20240801T143318, end_date=20240801T143319
[2024-08-01T14:33:19.565+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 12 for task upload_to_gcs (upload_to_gcs() missing 1 required positional argument: 'credentials'; 406)
[2024-08-01T14:33:19.639+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-08-01T14:33:19.811+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
