[2024-08-01T14:41:13.688+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T14:41:13.699+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_etl.clean_and_transform_data scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-08-01T14:41:13.708+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_etl.clean_and_transform_data scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-08-01T14:41:13.709+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-08-01T14:41:13.721+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): clean_and_transform_data> on 2023-01-01 00:00:00+00:00
[2024-08-01T14:41:13.732+0000] {standard_task_runner.py:57} INFO - Started process 813 to run task
[2024-08-01T14:41:13.738+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nyc_taxi_etl', 'clean_and_transform_data', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_etl.py', '--cfg-path', '/tmp/tmp4wmsauon']
[2024-08-01T14:41:13.740+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask clean_and_transform_data
[2024-08-01T14:41:13.756+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T14:41:13.794+0000] {task_command.py:410} INFO - Running <TaskInstance: nyc_taxi_etl.clean_and_transform_data scheduled__2023-01-01T00:00:00+00:00 [running]> on host 31f8257a797f
[2024-08-01T14:41:13.812+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-01T14:41:14.271+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_taxi_etl' AIRFLOW_CTX_TASK_ID='clean_and_transform_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2024-08-01T14:41:44.817+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-08-01T14:41:44.900+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=nyc_taxi_etl, task_id=clean_and_transform_data, execution_date=20230101T000000, start_date=20240801T144113, end_date=20240801T144144
[2024-08-01T14:41:45.089+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-08-01T14:41:45.229+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
